services:
  app:
    build: .
    volumes:
      - .:/workspace
      - ${HOME}/.gitconfig:/root/.gitconfig:ro
      - ${HOME}/.ssh:/root/.ssh:ro
    working_dir: /workspace
    stdin_open: true
    tty: true
